### ISSUE TITLE
Incorrect time schedule?

### ISSUE THREAD

**Issue by scheung38** [chfritz/meteor-easycron#11]
```
  var everyHour = new Cron(function() {
        console.log("it is 3 minutes past the hour"); 
    }, {
        minutes: 3
    });
```

but output is every minute ?

I20160503-11:00:00.869(1)? it is 3 minutes past the hour 

I20160503-11:01:00.881(1)? it is 3 minutes past the hour

I20160503-11:02:00.897(1)? it is 3 minutes past the hour

I20160503-11:03:00.914(1)? it is 3 minutes past the hour

**Comment by chfritz** [comment]
You have a typo: it's `minute`, not `minutes`.

**Comment by scheung38** [comment]
But if minute:2 it wont even call 
but if minutes:2: calls every minute?
but if leave empty then every minute
