### ISSUE TITLE
every 2 minutes instead of every minute?

### ISSUE THREAD

**Issue by scheung38** [chfritz/meteor-easycron#12]
I tried to modify so job is run every 2 minutes instead of the default every minute

```
var everyMinute = new Cron(function() {
    console.log("another minute has passed!");
}, {});
```

But now this would not run?

```
var every2Minute = new Cron(function() {
    console.log("Every 2 minute has passed!");
}, { minute: 2 });
```

**Comment by chfritz** [comment]
A cycle of "every two minutes" is not currently supported. It's not a typical cron pattern either. Your code is interpreted as every hour at 2 minutes past the hour.
