### ISSUE TITLE
no console.log

### ISSUE THREAD

**Issue by tcurdt** [chfritz/meteor-easycron#6]
Would be great to get rid of https://github.com/chfritz/meteor-easycron/blob/master/cron.js#L81 ...or at least only print it if a `verbose` or `debug` flag was set in the options.

Even nicer would be to pass the next tick to the callback function - then it's up to the user to print that information or not. That would not even need a configuration option then.

**Comment by chfritz** [comment]
good point. I'm working on something else right now, but if you want to create a pull request, go for it.

**Comment by chfritz** [comment]
Fixed in 3ad55726fa80c09e97e1d501c8086eb52feee3b9.
