### ISSUE TITLE
Every five minutes

### ISSUE THREAD

**Issue by kordianbruck** [chfritz/meteor-easycron#8]
How does one do this? 

In normal cron it would be */5 right? I tried passing it as a string, but no luck.

**Comment by chfritz** [comment]
I don't think that's currently possible, but could be added. Feel free to issue a pull-request if you are inclined to do so before I get to that (which may not be for a while).

**Comment by robertclarkson** [comment]
Heres a work around:

``` javascript
var everyFiveMin = new Cron(function() {
   console.log('5 min');
   runStuff();
}, {minute:0});
var everyFiveMin = new Cron(function() {
   console.log('5 min');
   runStuff();
}, {minute:5});
var everyFiveMin = new Cron(function() {
   console.log('5 min');
   runStuff();
}, {minute:10});

//and so on

```

Then just chuck all your shizzle in runstuff

**Comment by kordianbruck** [comment]
@robertclarkson thanks!
